name: Code quality Checks
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    lint-format-build:
        runs-on: ubuntu-latest
        env:
            HUSKY: 0
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "22"
            - name: Install dependencies
              run: npm install
            - name: Format Code
              run: npm run format
            - name: Lint Code
              run: npm run lint
            - name: Build Project
              run: npm run build
